1. Create a tensor `a` from `list(range(9))`. Print the tensor and display its shape.

In [2]:
import torch

a = torch.tensor(list(range(9)))
a, a.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]), torch.Size([9]))

2. Create a new tensor using `b = a.view(3, 3)`. Explain what `view` does to the tensor and display `b`.

In [ ]:
b = a.view(3, 3) # reshapes the tensor into a matrix shape without changing the data

b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

3. Change the first element of `b` to 100. Print `a` and `b`. Notice that tensor `a` is also affected by the assignment.

In [5]:
b[0, 0] = 100

print(f'A: {a}')
print(f'B: {b}')

A: tensor([100,   1,   2,   3,   4,   5,   6,   7,   8])
B: tensor([[100,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8]])


4. Find a function in the `torch` library that calculates the logrithm of numbers. Apply the function to tensor `a` and print the results.

In [6]:
funcA = torch.log(a)
print(funcA)

tensor([4.6052, 0.0000, 0.6931, 1.0986, 1.3863, 1.6094, 1.7918, 1.9459, 2.0794])
